// <auto-generated />
using System;
using FastCost.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastCost.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("FastCost.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "apartment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "shopping"
                        },
                        new
                        {
                            Id = 4,
                            Name = "transport"
                        },
                        new
                        {
                            Id = 5,
                            Name = "trip"
                        },
                        new
                        {
                            Id = 6,
                            Name = "bank"
                        },
                        new
                        {
                            Id = 7,
                            Name = "company"
                        },
                        new
                        {
                            Id = 8,
                            Name = "other"
                        });
                });

            modelBuilder.Entity("FastCost.DAL.Entities.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("costs");
                });

            modelBuilder.Entity("FastCost.DAL.Entities.Cost", b =>
                {
                    b.HasOne("FastCost.DAL.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
